version: "3.8"

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Message
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - default

  app:
    image: prg9:latest
    ports:
      -  8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/Message
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      - db
    networks:
      - default

